spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/todo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

logging:
  level:
    org.springframework.cache.interceptor: TRACE


