version: "3.8"

volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data